# 1. Numpy

## 1.1 Numpy介绍

NumPy(Numerical Python) 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。    
NumPy 是一个运行速度非常快的数学库，主要用于数组计算，具体：
1. 一个强大的N维数组对象 ndarray
2. 广播功能函数
3. 整合 C/C++/Fortran 代码的工具
4. 线性代数、傅里叶变换、随机数生成等功能


SciPy 是一个开源的 Python 算法库和数学工具包。SciPy 包含的模块有最优化、线性代数、积分、插值、特殊函数、快速傅里叶变换、信号处理和图像处理、常微分方程求解和其他科学与工程中常用的计算。    

Matplotlib 是 Python 编程语言及其数值数学扩展包 NumPy 的可视化操作界面。它为利用通用的图形用户界面工具包，如 Tkinter, wxPython, Qt 或 GTK+ 向应用程序嵌入式绘图提供了应用程序接口（API）。

参考：    
https://www.runoob.com/numpy/numpy-tutorial.html     
http://c.biancheng.net/numpy/

## 1.2 Ndarray 对象 

NumPy 定义了一个 n 维数组对象，是一个一系列相同类型元素组成的数组集合。数组中的每个元素都占有大小相同的内存块，并且可以使用索引或切片的方式获取数组中的每个元素。

创建对象

In [9]:
import numpy as np
# numpy.array(object, dtype = None, copy = True, order = None,ndmin = 0)
exam = np.array([[1,2,3],[4,5,6]])
print(exam)

print("--------------")

# 定义结构化数据
Stu = np.dtype([('name','S20'), ('age', 'i1')])
print(Stu)
stu_exam = np.array([('Zhangsan', 18),('Wuji', 28)], dtype = Stu) 
print(stu_exam)

[[1 2 3]
 [4 5 6]]
--------------
[('name', 'S20'), ('age', 'i1')]
[(b'Zhangsan', 18) (b'Wuji', 28)]


数组的维度

In [13]:
print(exam.shape)
print(exam.ndim)

(2, 3)
2


## 1.2 索引与切片

ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。    
ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。

In [37]:
# 举例
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [41]:
a[0:2][1]

array([3, 4, 5])

In [42]:
a[0][2]

3

In [17]:
# 整数数组索引
# 获取数组中(0,0)，(1,1)和(2,0)位置处的元素
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  
print (y)

[1 4 5]


## 1.3 计算

数学函数
1. NumPy 提供了标准的三角函数：sin()、cos()、tan()。
2. 舍入函数：numpy.around() 函数返回指定数字的四舍五入值。

In [19]:
# numpy.around(a,decimals)  decimals: 舍入的小数位数
a = np.array([1.0,  5.55, 123, 0.567, 25.532])  
print(np.around(a))

[  1.   6. 123.   1.  26.]


numpy.floor() 返回小于或者等于指定表达式的最大整数，即向下取整。     
numpy.ceil() 返回大于或者等于指定表达式的最小整数，即向上取整。 

算数函数   
1. NumPy 算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()。    
注意：数组必须具有相同的形状或符合数组广播规则。

In [20]:
a = np.array([10,100,1000])  
b = np.array([1,2,3])  
print (np.add(a,b))

[  11  102 1003]


统计函数    
1. numpy.amin() 用于计算数组中的元素沿指定轴的最小值。
2. numpy.amax() 用于计算数组中的元素沿指定轴的最大值。
3. numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。
4. numpy.percentile() 百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。
5. numpy.median() 函数用于计算数组 a 中元素的中位数（中值）
6. numpy.mean() 函数返回数组中元素的算术平均值。如果提供了轴，则沿其计算。算术平均值是沿轴的元素的总和除以元素的数量。
7. numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。
8. 标准差、方差：np.std\np.var

In [23]:
# numpy.percentile() 
a = np.array([[10, 7, 4], [3, 2, 1]])
# 50% 的分位数
print (np.percentile(a, 50))
# axis 为 0，在纵列上求
print (np.percentile(a, 50, axis=0)) 
# axis 为 1，在横行上求
print (np.percentile(a, 50, axis=1)) 

3.5
[6.5 4.5 2.5]
[7. 2.]


In [26]:
# numpy.average()
a = np.array([1,2,3,4]) 
# 若不指定权重相当于对数组求均值
print (np.average(a))

we = np.array([4,3,2,1]) 
print(np.average(a,weights = we))

2.5
2.0


## 1.4 NumPy 中的广播机制（Broadcast）
旨在解决不同形状数组之间的算术运算问题。   
这种机制的核心是对形状较小的数组，在横向或纵向上进行一定次数的重复，使其与形状较大的数组拥有相同的维度。

In [27]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])

b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
